services:
  fullcycle:
    image: postgres:16.2-alpine3.18
    container_name: fullcycle
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  migrate:
    image: migrate/migrate
    depends_on:
      fullcycle:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:password@fullcycle:5432/postgres?sslmode=disable", "up" ]
    links:
      - fullcycle

networks:
  app-network:
     driver: bridge